import { type NextPage } from "next";
import Head from "next/head";
import { useQRCode } from "next-qrcode";
import Link from "next/link";

function t(time: string, text: string) {
  let seconds = 0;
  let minutes = 0;
  if (time.includes(":")) {
    const split = time.split(":");
    minutes = parseInt(split[0] as string);
    seconds = parseInt(split[1] as string);
  } else {
    seconds = parseInt(time);
  }
  return { time: minutes * 60 + seconds, text };
}

const TIME_STAMPS = [
  t("0", "Byrjun myndband"),
  t("8", "Upphitun"),
  t("13", "Upphitun - Cat & cow"),
  t("37", "Upphitun - Psoas opnun + rassvöðva virkjun"),
  t("1:05", "Upphitun - Glute með virkjun"),
  t("1:43", "Upphitun - Hip flexor virkjun"),
  t("2:11", "Styrktaræfingar"),
  t("2:16", "Styrktaræfingar - Glute bridge"),
  t("2:55", "Styrktaræfingar - Reverse hyper"),
  t("3:35", "Styrktaræfingar - Hyper extension"),
  t("4:11", "Styrktaræfingar - Russian twist"),
  t("4:57", "Styrktaræfingar - Hliðar planki"),
  t("5:43", "Styrktaræfingar - Pallof æfingar"),
  t("7:04", "Styrktaræfingar - Adductor ball squeeze"),
  t("7:26", "Liðleikaæfingar"),
  t("7:30", "Liðleikaæfingar - Banded joint mobilization"),
  t("8:06", "Liðleikaæfingar - Piriformis stretch"),
  t("8:24", "Liðleikaæfingar - Pigeon pose stretch & mobilization"),
  t("9:14", "Liðleikaæfingar - Kettlebell weight shift"),
  t("9:52", "Liðleikaæfingar - Psoas opnun"),
  t("10:26", "Liðleikaæfingar - T-spine box stretch"),
  t("11:05", "Liðleikaæfingar - T-spine opnun með priki"),
  t("11:35", "Liðleikaæfingar - T-spine opnun á gólfi"),
  t("12:06", "Liðleikaæfingar - T-spine opnun með ketilbjöllu"),
  t("12:30", "Stöðuleikaæfingar"),
  t("12:35", "Stöðuleikaæfingar - Bird dog"),
  t("13:28:", "Stöðuleikaæfingar - Dead bug"),
  t("14:42", "Stöðuleikaæfingar - Suitcase carry"),
  t("15:24", "Stöðuleikaæfingar - Mcgill curl up"),
  t("15:56", "Stöðuleikaæfingar - Plank variations"),
  t("16:52", "Stöðuleikaæfingar - Kettlebell wrap around"),
  t("17:13", "Stöðuleikaæfingar - Renegade row"),
  t("17:37", "Vöðvalosun"),
  t("17:42", "Vöðvalosun - Brjóstbaks losun"),
  t("18:17", "Vöðvalosun - Piriformis losun"),
  t("18:43", "Vöðvalosun - Psoas losun"),
  t("19:13", "Vöðvalosun - Quadratus lumborum losun"),
  t("19:39", "Vöðvalosun - Adductor losun"),
  t("19:59", "Vöðvalosun - IT-band losun"),
  t("20:13", "Próf"),
  t("20:18", "Próf - Faber test"),
  t("20:42", "Próf - Thomas test"),
  t("20:58", "Próf - Load test"),
  t("21:14", "Próf - Single leg glute bridge test"),
  t("21:29", "Próf - Internal & external hip rotation test"),
  t("21:59", "Próf - T-spine rotation test"),
  t("22:21", "Próf - Flexion & extension intolerance test"),
  t("22:47", "Próf - Abductor manual muscle test"),
  t("23:09", "Próf - Adductor manual muscle test"),
  t("23:32", "Takk fyrir okkur Eyþór og Valgarð"),
];

const Home: NextPage = () => {
  const { Canvas } = useQRCode();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div
          className={
            "flex flex-row flex-wrap items-center justify-center gap-4"
          }
        >
          {TIME_STAMPS.map((timestamp) => (
            <div
              key={timestamp.text}
              className={"flex flex-col items-center gap-2 rounded border p-4"}
            >
              <p className={"text-center"}>{timestamp.text}</p>
              <Canvas
                key={timestamp.text}
                text={`https://youtu.be/qpHDBmV6Ppw?t=${timestamp.time}`}
                options={{
                  level: "M",
                  margin: 3,
                  scale: 4,
                  width: 200,
                  color: {
                    dark: "#000000",
                    light: "#ffffff",
                  },
                }}
              />
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
